### PR TITLE
add Pake ChatGPT APP, and update OpenCat

### PR DESCRIPTION
**Pull request by rubickecho**

### CODE REVIEW

**Comment by reorx** [comment]
Hi, I think you forgot to replace the copied url with yours

**Comment by peakcool** [comment]
sorry, I was too careless, it has been updated.

**Comment by reorx** [comment]
wait…I suppose you want to submit an application built with Pake, not Pake itself right?

**Comment by rubickecho** [comment]
yes, just ChatGPT App，but I didn't find its unique link.

**Comment by reorx** [comment]
If so, it does not meet the collection standard because:
1. It's a wrapper around the ChatGPT web app, which cannot customize the API key.
2. It does not have a dedicated website or project page.

But anyway, thanks for your contribution!

**Pull request closed without merging**
